"""
Hardcoded onboarding demo playbooks — deterministic, no LLM generation.
"""

from __future__ import annotations

from typing import Any

EXCELLENT_TRACE: dict[str, Any] = {
    "metadata": {
        "run_id": "demo-excellent-001",
        "framework": "generic",
        "started_at": "2024-08-01T09:00:00Z",
        "completed_at": "2024-08-01T09:00:04Z",
        "status": "success",
        "agent_name": "EfficientAgent",
    },
    "available_tools": [
        {"name": "Weather", "description": "Get weather for a city"},
        {"name": "Calculator", "description": "Math operations"},
    ],
    "steps": [
        {
            "index": 0,
            "type": "thought",
            "node_name": "planner",
            "content": "User wants SF weather. Single Weather tool call is sufficient.",
            "stage": "planning",
            "duration_ms": 120,
            "tokens": {"prompt": 80, "completion": 30},
        },
        {
            "index": 1,
            "type": "state_transition",
            "node_name": "planner",
            "state_from": "planner",
            "state_to": "executor",
            "duration_ms": 5,
        },
        {
            "index": 2,
            "type": "tool_call",
            "node_name": "executor",
            "tool_name": "Weather",
            "tool_input": {"location": "San Francisco, CA"},
            "stage": "execution",
            "duration_ms": 890,
            "tokens": {"prompt": 100, "completion": 20},
        },
        {
            "index": 3,
            "type": "tool_result",
            "node_name": "executor",
            "tool_name": "Weather",
            "tool_output": {"temp_f": 62, "condition": "Sunny"},
            "stage": "execution",
            "duration_ms": 15,
        },
        {
            "index": 4,
            "type": "thought",
            "node_name": "synthesizer",
            "content": "San Francisco is 62°F and sunny. Task complete.",
            "stage": "synthesis",
            "duration_ms": 95,
            "tokens": {"prompt": 140, "completion": 35},
        },
    ],
}

CHAOTIC_TRACE: dict[str, Any] = {
    "metadata": {
        "run_id": "demo-chaotic-prod-fail",
        "framework": "generic",
        "started_at": "2024-08-01T14:22:00Z",
        "completed_at": "2024-08-01T14:29:41Z",
        "status": "failure",
        "agent_name": "ProductionResearchAgent",
    },
    "available_tools": [
        {"name": "Search", "description": "Web search"},
        {"name": "Weather", "description": "Weather API"},
    ],
    "steps": [
        {
            "index": 0,
            "type": "thought",
            "node_name": "planner",
            "content": "Need weather data for San Francisco production incident triage.",
            "stage": "planning",
            "duration_ms": 2400,
            "tokens": {"prompt": 12000, "completion": 3200},
            "cost_usd": 0.0088,
        },
        {
            "index": 1,
            "type": "thought",
            "node_name": "planner",
            "content": "Need weather information for San Francisco production incident triage.",
            "stage": "planning",
            "duration_ms": 2100,
            "tokens": {"prompt": 14000, "completion": 3100},
            "cost_usd": 0.0090,
        },
        {
            "index": 2,
            "type": "thought",
            "node_name": "planner",
            "content": "Need weather forecast for San Francisco production incident triage.",
            "stage": "planning",
            "duration_ms": 2050,
            "tokens": {"prompt": 15000, "completion": 3000},
            "cost_usd": 0.0091,
        },
        {
            "index": 3,
            "type": "thought",
            "node_name": "planner",
            "content": "Need weather data for San Francisco production incident response.",
            "stage": "planning",
            "duration_ms": 1980,
            "tokens": {"prompt": 16000, "completion": 2900},
            "cost_usd": 0.0091,
        },
        {
            "index": 4,
            "type": "thought",
            "node_name": "planner",
            "content": "Need weather information for San Francisco production incident response.",
            "stage": "planning",
            "duration_ms": 1920,
            "tokens": {"prompt": 17000, "completion": 2800},
            "cost_usd": 0.0092,
        },
        {
            "index": 5,
            "type": "state_transition",
            "node_name": "planner",
            "state_from": "planner",
            "state_to": "retriever",
            "duration_ms": 8,
        },
        {
            "index": 6,
            "type": "tool_call",
            "node_name": "retriever",
            "tool_name": "Search",
            "tool_input": {"query": "SF weather incident"},
            "stage": "retrieval",
            "duration_ms": 4200,
            "tokens": {"prompt": 8000, "completion": 400},
            "cost_usd": 0.0034,
        },
        {
            "index": 7,
            "type": "tool_result",
            "node_name": "retriever",
            "tool_name": "Search",
            "tool_output": {"results": ["62F partly cloudy"]},
            "stage": "retrieval",
            "duration_ms": 120,
        },
        {
            "index": 8,
            "type": "tool_call",
            "node_name": "retriever",
            "tool_name": "Search",
            "tool_input": {"query": "SF weather incident"},
            "stage": "retrieval",
            "duration_ms": 4100,
            "tokens": {"prompt": 8500, "completion": 400},
            "cost_usd": 0.0035,
        },
        {
            "index": 9,
            "type": "tool_result",
            "node_name": "retriever",
            "tool_name": "Search",
            "tool_output": {"results": ["62F partly cloudy"]},
            "stage": "retrieval",
            "duration_ms": 110,
        },
        {
            "index": 10,
            "type": "tool_call",
            "node_name": "retriever",
            "tool_name": "Search",
            "tool_input": {"query": "San Francisco weather now"},
            "stage": "retrieval",
            "duration_ms": 4300,
            "tokens": {"prompt": 9000, "completion": 420},
            "cost_usd": 0.0036,
        },
        {
            "index": 11,
            "type": "tool_result",
            "node_name": "retriever",
            "tool_name": "Search",
            "tool_output": {"results": ["62F partly cloudy"]},
            "stage": "retrieval",
            "duration_ms": 105,
        },
        {
            "index": 12,
            "type": "tool_call",
            "node_name": "retriever",
            "tool_name": "Search",
            "tool_input": {"query": "current weather San Francisco"},
            "stage": "retrieval",
            "duration_ms": 4400,
            "tokens": {"prompt": 9500, "completion": 430},
            "cost_usd": 0.0037,
        },
        {
            "index": 13,
            "type": "tool_result",
            "node_name": "retriever",
            "tool_name": "Search",
            "tool_output": {"results": ["62F partly cloudy"]},
            "stage": "retrieval",
            "duration_ms": 100,
        },
        {
            "index": 14,
            "type": "state_transition",
            "node_name": "retriever",
            "state_from": "retriever",
            "state_to": "executor",
            "duration_ms": 6,
        },
        {
            "index": 15,
            "type": "tool_call",
            "node_name": "executor",
            "tool_name": "Weather",
            "tool_input": {"location": "San Francisco"},
            "stage": "execution",
            "duration_ms": 12000,
            "tokens": {"prompt": 6000, "completion": 300},
            "cost_usd": 0.0011,
        },
        {
            "index": 16,
            "type": "tool_result",
            "node_name": "executor",
            "tool_name": "Weather",
            "tool_output": {
                "error": "RateLimitExceeded",
                "exception": "HTTP 429: API quota exhausted after retrieval loop",
                "status": "failure",
            },
            "stage": "execution",
            "duration_ms": 45,
        },
        {
            "index": 17,
            "type": "thought",
            "node_name": "executor",
            "content": "Weather API failed. Cannot complete incident triage.",
            "stage": "synthesis",
            "duration_ms": 800,
            "tokens": {"prompt": 2000, "completion": 200},
            "cost_usd": 0.0004,
        },
    ],
}


def get_excellent_trace() -> dict[str, Any]:
    return EXCELLENT_TRACE.copy()


def get_chaotic_trace() -> dict[str, Any]:
    return CHAOTIC_TRACE.copy()
